services:
  sorepy:
    image: phaenos/sorepy
    container_name: sorepy
    ports:
      - "5000:5000"
    volumes:
      - /sorepy/data:./sorepy/data
    networks:
      - default
    restart: unless-stopped

